{% set name = "itkwasm-downsample-wasi" %}
{% set version = "2.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/i/itkwasm-downsample-wasi/itkwasm_downsample_wasi-{{ version }}.tar.gz
  sha256: b0f60ee4a243ecfb897406a8086c12563d1844cf665722994d0c95a82601b785

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - itkwasm
    - importlib-resources

test:
  imports:
    - itkwasm_downsample_wasi
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/itkwasm-downsample-wasi/
  summary: Pipelines for downsampling images.
  dev_url: https://github.com/InsightSoftwareConsortium/ITK-Wasm
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - khaled196
    - thewtex
